# school_region.py

REGION_MAP = {
    # I. Hà Nội
    'QHL': 'Hà Nội', 'QHQ': 'Hà Nội', 'QHY': 'Hà Nội', 'QHI': 'Hà Nội',
    'QHE': 'Hà Nội', 'QHS': 'Hà Nội', 'QHT': 'Hà Nội', 'QHX': 'Hà Nội',
    'QHD': 'Hà Nội', 'QHF': 'Hà Nội', 'VJU': 'Hà Nội', 'NVH': 'Hà Nội',
    'HBT': 'Hà Nội', 'HCP': 'Hà Nội', 'BVH': 'Hà Nội', 'HCH': 'Hà Nội',
    'KMA': 'Hà Nội', 'NHH': 'Hà Nội', 'HQT': 'Hà Nội', 'HVN': 'Hà Nội',
    'HPN': 'Hà Nội', 'HVQ': 'Hà Nội', 'HTC': 'Hà Nội', 'HTN': 'Hà Nội',
    'HTA': 'Hà Nội', 'HYD': 'Hà Nội', 'BKA': 'Hà Nội', 'LDA': 'Hà Nội',
    'GTA': 'Hà Nội', 'CCM': 'Hà Nội', 'DCN': 'Hà Nội', 'VHD': 'Hà Nội',
    'DDN': 'Hà Nội', 'DDL': 'Hà Nội', 'DKH': 'Hà Nội', 'FPT': 'Hà Nội',
    'GHA': 'Hà Nội', 'NHF': 'Hà Nội', 'ETU': 'Hà Nội', 'KCN': 'Hà Nội',
    'DKS': 'Hà Nội', 'KTA': 'Hà Nội', 'DKK': 'Hà Nội', 'KHA': 'Hà Nội',
    'LNH': 'Hà Nội', 'DLX': 'Hà Nội', 'LPH': 'Hà Nội', 'MDA': 'Hà Nội',
    'MTC': 'Hà Nội', 'MTH': 'Hà Nội', 'NTH': 'Hà Nội', 'NTU': 'Hà Nội',
    'SKD': 'Hà Nội', 'SPH': 'Hà Nội', 'GNT': 'Hà Nội', 'TDH': 'Hà Nội',
    'FBU': 'Hà Nội', 'DMT': 'Hà Nội', 'DTL': 'Hà Nội', 'TDD': 'Hà Nội',
    'HNM': 'Hà Nội', 'TMU': 'Hà Nội', 'TLA': 'Hà Nội', 'VHH': 'Hà Nội',
    'XDA': 'Hà Nội', 'YHB': 'Hà Nội', 'YTC': 'Hà Nội', 'DCQ': 'Hà Nội',
    'DDU': 'Hà Nội', 'DQK': 'Hà Nội', 'DPD': 'Hà Nội', 'MHN': 'Hà Nội',
    'PKA': 'Hà Nội', 'CMC': 'Hà Nội',

    # II. TP.HCM
    'QSY': 'TP.HCM', 'QSB': 'TP.HCM', 'QSC': 'TP.HCM', 'QST': 'TP.HCM',
    'QSX': 'TP.HCM', 'QSQ': 'TP.HCM', 'QSK': 'TP.HCM', 'HVC': 'TP.HCM',
    'BVS': 'TP.HCM', 'HHK': 'TP.HCM', 'NVS': 'TP.HCM', 'DCT': 'TP.HCM',
    'IUH': 'TP.HCM', 'GSA': 'TP.HCM', 'GTS': 'TP.HCM', 'HSU': 'TP.HCM',
    'KTS': 'TP.HCM', 'UEF': 'TP.HCM', 'KSA': 'TP.HCM', 'DLS': 'TP.HCM',
    'LPS': 'TP.HCM', 'MBS': 'TP.HCM', 'MTS': 'TP.HCM', 'NHS': 'TP.HCM',
    'NTS': 'TP.HCM', 'NTT': 'TP.HCM', 'NLS': 'TP.HCM', 'HIU': 'TP.HCM',
    'SGD': 'TP.HCM', 'DSD': 'TP.HCM', 'SPK': 'TP.HCM', 'SPS': 'TP.HCM',
    'DMS': 'TP.HCM', 'DTM': 'TP.HCM', 'TDS': 'TP.HCM', 'TLS': 'TP.HCM',
    'DTT': 'TP.HCM', 'VHS': 'TP.HCM', 'VGU': 'TP.HCM', 'YDS': 'TP.HCM',
    'TYS': 'TP.HCM', 'DSG': 'TP.HCM', 'GDU': 'TP.HCM', 'DKC': 'TP.HCM',
    'DHV': 'TP.HCM', 'SIU': 'TP.HCM', 'DVH': 'TP.HCM', 'DVL': 'TP.HCM',
    'STS': 'TP.HCM', 'DNT': 'TP.HCM', 'UMT': 'TP.HCM',

    # III. Miền Bắc
    'DTF': 'Miền Bắc', 'DTQ': 'Miền Bắc', 'DTP': 'Miền Bắc', 'DTC': 'Miền Bắc',
    'DTZ': 'Miền Bắc', 'DTE': 'Miền Bắc', 'DTK': 'Miền Bắc', 'DTN': 'Miền Bắc',
    'DTS': 'Miền Bắc', 'DTY': 'Miền Bắc', 'DCA': 'Miền Bắc', 'DDA': 'Miền Bắc',
    'DDM': 'Miền Bắc', 'VUI': 'Miền Bắc', 'DHP': 'Miền Bắc', 'DTV': 'Miền Bắc',
    'YDD': 'Miền Bắc', 'HLU': 'Miền Bắc', 'DKT': 'Miền Bắc', 'THP': 'Miền Bắc',
    'HHA': 'Miền Bắc', 'DNB': 'Miền Bắc', 'HDT': 'Miền Bắc', 'THV': 'Miền Bắc',
    'UKB': 'Miền Bắc', 'DKY': 'Miền Bắc', 'DBG': 'Miền Bắc', 'DBH': 'Miền Bắc',
    'SDU': 'Miền Bắc', 'SP2': 'Miền Bắc', 'SKH': 'Miền Bắc', 'SKN': 'Miền Bắc',
    'DFA': 'Miền Bắc', 'TQU': 'Miền Bắc', 'TTB': 'Miền Bắc', 'DTB': 'Miền Bắc',
    'DDB': 'Miền Bắc', 'TDB': 'Miền Bắc', 'DVP': 'Miền Bắc', 'DVD': 'Miền Bắc',
    'DVB': 'Miền Bắc', 'YPB': 'Miền Bắc', 'YTB': 'Miền Bắc', 'THU': 'Miền Bắc',

    # IV. Miền Nam
    'TAG': 'Miền Nam', 'BVU': 'Miền Nam', 'DBL': 'Miền Nam', 'DBD': 'Miền Nam',
    'TCT': 'Miền Nam', 'DCD': 'Miền Nam', 'MIT': 'Miền Nam', 'DCL': 'Miền Nam',
    'DLH': 'Miền Nam', 'PVU': 'Miền Nam', 'DNU': 'Miền Nam', 'SPD': 'Miền Nam',
    'TKG': 'Miền Nam', 'DLA': 'Miền Nam', 'DKB': 'Miền Nam', 'KCC': 'Miền Nam',
    'LNS': 'Miền Nam', 'DNC': 'Miền Nam', 'EIU': 'Miền Nam', 'VLU': 'Miền Nam',
    'TTU': 'Miền Nam', 'DTD': 'Miền Nam', 'TDM': 'Miền Nam', 'TTG': 'Miền Nam',
    'DVT': 'Miền Nam', 'VGU': 'Miền Nam', 'VTT': 'Miền Nam', 'MTU': 'Miền Nam',
    'YCT': 'Miền Nam',

    # V. Miền Trung - Tây Nguyên
    'DHD': 'Miền Trung - Tây Nguyên', 'DHC': 'Miền Trung - Tây Nguyên',
    'DHT': 'Miền Trung - Tây Nguyên', 'DHK': 'Miền Trung - Tây Nguyên',
    'DHL': 'Miền Trung - Tây Nguyên', 'DHN': 'Miền Trung - Tây Nguyên',
    'DHA': 'Miền Trung - Tây Nguyên', 'DHF': 'Miền Trung - Tây Nguyên',
    'DHS': 'Miền Trung - Tây Nguyên', 'DHY': 'Miền Trung - Tây Nguyên',
    'DHE': 'Miền Trung - Tây Nguyên', 'DHI': 'Miền Trung - Tây Nguyên',
    'DHQ': 'Miền Trung - Tây Nguyên', 'DDG': 'Miền Trung - Tây Nguyên',
    'DDY': 'Miền Trung - Tây Nguyên', 'DDP': 'Miền Trung - Tây Nguyên',
    'DDK': 'Miền Trung - Tây Nguyên', 'DDQ': 'Miền Trung - Tây Nguyên',
    'DDF': 'Miền Trung - Tây Nguyên', 'DDS': 'Miền Trung - Tây Nguyên',
    'DSK': 'Miền Trung - Tây Nguyên', 'DDV': 'Miền Trung - Tây Nguyên',
    'VKU': 'Miền Trung - Tây Nguyên', 'KTD': 'Miền Trung - Tây Nguyên',
    'BMU': 'Miền Trung - Tây Nguyên', 'DVX': 'Miền Trung - Tây Nguyên',
    'DCV': 'Miền Trung - Tây Nguyên', 'TDL': 'Miền Trung - Tây Nguyên',
    'DDT': 'Miền Trung - Tây Nguyên', 'DPX': 'Miền Trung - Tây Nguyên',
    'DYD': 'Miền Trung - Tây Nguyên', 'DAD': 'Miền Trung - Tây Nguyên',
    'HHT': 'Miền Trung - Tây Nguyên', 'UKH': 'Miền Trung - Tây Nguyên',
    'CEA': 'Miền Trung - Tây Nguyên', 'YDN': 'Miền Trung - Tây Nguyên',
    'HVA': 'Miền Trung - Tây Nguyên', 'TSN': 'Miền Trung - Tây Nguyên',
    'DPQ': 'Miền Trung - Tây Nguyên', 'DPC': 'Miền Trung - Tây Nguyên',
    'DPT': 'Miền Trung - Tây Nguyên', 'DPY': 'Miền Trung - Tây Nguyên',
    'DQB': 'Miền Trung - Tây Nguyên', 'DQU': 'Miền Trung - Tây Nguyên',
    'DQT': 'Miền Trung - Tây Nguyên', 'DQN': 'Miền Trung - Tây Nguyên',
    'SKV': 'Miền Trung - Tây Nguyên', 'UFA': 'Miền Trung - Tây Nguyên',
    'TTN': 'Miền Trung - Tây Nguyên', 'TBD': 'Miền Trung - Tây Nguyên',
    'TTD': 'Miền Trung - Tây Nguyên', 'TDV': 'Miền Trung - Tây Nguyên',
    'XDT': 'Miền Trung - Tây Nguyên', 'YKV': 'Miền Trung - Tây Nguyên',

    # VI. Quân đội - Công an
    'BPH': 'Quân đội - Công an', 'HQH': 'Quân đội - Công an',
    'HEH': 'Quân đội - Công an', 'NQH': 'Quân đội - Công an',
    'KQH': 'Quân đội - Công an', 'PKH': 'Quân đội - Công an',
    'YQH': 'Quân đội - Công an', 'LCH': 'Quân đội - Công an',
    'ZNH': 'Quân đội - Công an', 'SNH': 'Quân đội - Công an',
    'DCH': 'Quân đội - Công an', 'KGH': 'Quân đội - Công an',
    'VPH': 'Quân đội - Công an', 'LAH': 'Quân đội - Công an',
    'LBH': 'Quân đội - Công an', 'PBH': 'Quân đội - Công an',
    'HGH': 'Quân đội - Công an', 'TGH': 'Quân đội - Công an',
    'TTH': 'Quân đội - Công an', 'ANH': 'Quân đội - Công an',
    'CSH': 'Quân đội - Công an', 'HCA': 'Quân đội - Công an',
    'ANS': 'Quân đội - Công an', 'CSS': 'Quân đội - Công an',
    'HCB': 'Quân đội - Công an', 'HCN': 'Quân đội - Công an',
    'PCH': 'Quân đội - Công an', 'PCS': 'Quân đội - Công an',

    # Các đại học vùng (thường không có điểm chuẩn riêng)
    'VNU': 'Hà Nội',
    'VNU-HCM': 'TP.HCM',
    'TNU': 'Miền Bắc',
    'HueUni': 'Miền Trung - Tây Nguyên',
    'UDN': 'Miền Trung - Tây Nguyên',
}

# Tên đầy đủ của từng mã trường (dựa trên danh sách bạn cung cấp)
SCHOOL_NAME_MAP = {
    # I. Hà Nội
    'QHL': 'Khoa Luật (ĐHQG Hà Nội)',
    'QHQ': 'Khoa Quốc tế (ĐHQG Hà Nội)',
    'QHY': 'Trường Đại học Y Dược (ĐHQG Hà Nội)',
    'QHI': 'Trường Đại học Công nghệ (ĐHQG Hà Nội)',
    'QHE': 'Trường Đại học Kinh tế (ĐHQG Hà Nội)',
    'QHS': 'Trường ĐH Giáo dục (ĐHQG Hà Nội)',
    'QHT': 'Trường ĐH Khoa học Tự nhiên (ĐHQG Hà Nội)',
    'QHX': 'Trường ĐH Khoa học Xã hội và Nhân văn (ĐHQG Hà Nội)',
    'QHD': 'Trường Quản trị và kinh doanh (ĐHQG Hà Nội)',
    'QHF': 'Trường Đại học Ngoại ngữ (ĐHQG Hà Nội)',
    'VJU': 'Trường Đại học Việt Nhật (ĐHQG Hà Nội)',
    'NVH': 'Học viện Âm nhạc Quốc gia Việt Nam',
    'HBT': 'Học viện Báo chí Tuyên truyền',
    'HCP': 'Học viện Chính sách và Phát triển',
    'BVH': 'Học viện Công nghệ Bưu chính Viễn thông',
    'HCH': 'Học viện Hành chính Quốc gia',
    'KMA': 'Học viện Kỹ thuật Mật mã',
    'NHH': 'Học viện Ngân hàng',
    'HQT': 'Học viện Ngoại giao',
    'HVN': 'Học viện Nông nghiệp Việt Nam',
    'HPN': 'Học viện Phụ nữ Việt Nam',
    'HVQ': 'Học viện Quản lý Giáo dục',
    'HTC': 'Học viện Tài chính',
    'HTN': 'Học viện Thanh Thiếu niên Việt Nam',
    'HTA': 'Học viện Tòa án',
    'HYD': 'Học viện Y Dược học cổ truyền Việt Nam',
    'BKA': 'Đại học Bách khoa Hà Nội',
    'LDA': 'Trường Đại học Công đoàn',
    'GTA': 'Trường Đại học Công nghệ Giao thông vận tải',
    'CCM': 'Trường Đại học Công nghiệp Dệt may Hà Nội',
    'DCN': 'Trường Đại học Công nghiệp Hà Nội',
    'VHD': 'Trường Đại học Công nghiệp Việt Hung',
    'DDN': 'Trường Đại học Đại Nam (*)',
    'DDL': 'Trường Đại học Điện lực',
    'DKH': 'Trường Đại học Dược Hà Nội',
    'FPT': 'Trường Đại học FPT (*)',
    'GHA': 'Trường Đại học Giao thông vận tải',
    'NHF': 'Trường Đại học Hà Nội',
    'ETU': 'Trường Đại học Hòa Bình (*)',
    'KCN': 'Trường Đại học Khoa học và Công nghệ Hà Nội',
    'DKS': 'Trường Đại học Kiểm sát Hà Nội',
    'KTA': 'Trường Đại học Kiến trúc Hà Nội',
    'DKK': 'Trường Đại học Kinh tế Kỹ thuật Công nghiệp',
    'KHA': 'Trường Đại học Kinh tế Quốc dân',
    'LNH': 'Trường Đại học Lâm nghiệp',
    'DLX': 'Trường Đại học Lao động Xã hội',
    'LPH': 'Trường Đại học Luật Hà Nội',
    'MDA': 'Trường Đại học Mỏ Địa chất Hà Nội',
    'MTC': 'Trường Đại học Mỹ thuật Công nghiệp',
    'MTH': 'Trường Đại học Mỹ thuật Việt Nam',
    'NTH': 'Trường Đại học Ngoại thương',
    'NTU': 'Trường Đại học Nguyễn Trãi (*)',
    'SKD': 'Trường Đại học Sân khấu Điện ảnh',
    'SPH': 'Trường Đại học Sư phạm Hà Nội',
    'GNT': 'Trường Đại học Sư phạm Nghệ thuật Trung ương Hà Nội',
    'TDH': 'Trường Đại học Sư phạm Thể dục thể thao Hà Nội',
    'FBU': 'Trường Đại học Tài chính Ngân hàng Hà Nội (*)',
    'DMT': 'Trường Đại học Tài nguyên và Môi trường Hà Nội',
    'DTL': 'Trường Đại học Thăng Long (*)',
    'TDD': 'Trường Đại học Thành Đô (*)',
    'HNM': 'Trường Đại học Thủ đô Hà Nội',
    'TMU': 'Trường Đại học Thương mại',
    'TLA': 'Trường Đại học Thủy lợi',
    'VHH': 'Trường Đại học Văn hóa Hà Nội',
    'XDA': 'Trường Đại học Xây dựng Hà Nội',
    'YHB': 'Trường Đại học Y Hà Nội',
    'YTC': 'Trường Đại học Y tế Công cộng',
    'DCQ': 'Trường Đại học Công nghệ và Quản lý Hữu nghị (*)',
    'DDU': 'Trường Đại học Đông Đô (*)',
    'DQK': 'Trường Đại học Kinh doanh và Công nghệ Hà Nội (*)',
    'DPD': 'Trường Đại học Phương Đông (*)',
    'MHN': 'Trường Đại học Mở Hà Nội',
    'PKA': 'Trường Đại học Phenikaa',
    'CMC': 'Trường Đại học CMC',

    # II. TP.HCM
    'QSY': 'Khoa Y - ĐH Quốc gia TP.HCM',
    'QSB': 'Trường Đại học Bách Khoa - ĐHQG TP.HCM',
    'QSC': 'Trường Đại học Công nghệ Thông tin - ĐH Quốc gia TP.HCM',
    'QST': 'Trường Đại học Khoa học Tự nhiên - ĐHQG TPHCM',
    'QSX': 'Trường Đại học Khoa học xã hội và Nhân văn - ĐHQG TP.HCM',
    'QSQ': 'Trường Đại học Quốc tế - ĐH Quốc gia TP.HCM',
    'QSK': 'Trường Đại học Kinh tế - Luật (ĐH Quốc gia TP.HCM)',
    'HVC': 'Học viện Cán bộ TP.HCM',
    'BVS': 'Học viện Công nghệ Bưu chính Viễn thông – Cơ sở TP.HCM',
    'HHK': 'Học viện Hàng không Việt Nam',
    'NVS': 'Nhạc viện TP.HCM',
    'DCT': 'Trường Đại học Công thương TP.HCM',
    'IUH': 'Trường Đại học Công nghiệp TP.HCM',
    'GSA': 'Trường Đại học Giao thông vận tải - Cơ sở 2',
    'GTS': 'Trường Đại học Giao thông vận tải TP.HCM',
    'HSU': 'Trường Đại học Hoa Sen (*)',
    'KTS': 'Trường Đại học Kiến trúc TP.HCM',
    'UEF': 'Trường Đại học Kinh tế - Tài chính TP.HCM (*)',
    'KSA': 'Trường Đại học Kinh tế TP.HCM',
    'DLS': 'Trường Đại học Lao động Xã hội – Cơ sở TP.HCM',
    'LPS': 'Trường Đại học Luật TP.HCM',
    'MBS': 'Trường Đại học Mở TP.HCM',
    'MTS': 'Trường Đại học Mỹ thuật TP.HCM',
    'NHS': 'Trường Đại học Ngân hàng TP.HCM',
    'NTS': 'Trường Đại học Ngoại thương – Cơ sở phía Nam',
    'NTT': 'Trường Đại học Nguyễn Tất Thành (*)',
    'NLS': 'Trường Đại học Nông Lâm TP.HCM',
    'HIU': 'Trường Đại học Quốc tế Hồng Bàng (*)',
    'SGD': 'Trường Đại học Sài Gòn',
    'DSD': 'Trường Đại học Sân khấu Điện ảnh TP.HCM',
    'SPK': 'Trường Đại học Sư phạm Kỹ thuật TP.HCM',
    'SPS': 'Trường Đại học Sư phạm TP.HCM',
    'DMS': 'Trường Đại học Tài chính - Marketing',
    'DTM': 'Trường Đại học Tài nguyên và Môi trường TP.HCM',
    'TDS': 'Trường Đại học Thể dục Thể thao TP.HCM',
    'TLS': 'Trường Đại học Thủy lợi – Cơ sở 2',
    'DTT': 'Trường Đại học Tôn Đức Thắng',
    'VHS': 'Trường Đại học Văn hóa TP.HCM',
    'VGU': 'Trường Đại học Việt - Đức',  # Có thể map chung cho Miền Nam
    'YDS': 'Trường Đại học Y Dược TP.HCM',
    'TYS': 'Trường Đại học Y khoa Phạm Ngọc Thạch',
    'DSG': 'Trường Đại học Công nghệ Sài Gòn (*)',
    'GDU': 'Trường Đại học Gia Định (*)',
    'DKC': 'Trường Đại học Công nghệ TP.HCM (*)',
    'DHV': 'Trường Đại học Hùng Vương TPHCM (*)',
    'SIU': 'Trường Đại học Quốc tế Sài Gòn (*)',
    'DVH': 'Trường Đại học Văn Hiến (*)',
    'DVL': 'Trường Đại học Văn Lang (*)',
    'STS': 'Trường Đại học Sư phạm TDTT TP. HCM',
    'DNT': 'Trường Đại học Ngoại ngữ - Tin học TP.HCM (*)',
    'UMT': 'Trường Đại học Quản lý và công nghệ TPHCM',

    # III. Miền Bắc
    'DTF': 'Trường Ngoại ngữ (ĐH Thái Nguyên)',
    'DTQ': 'Khoa Quốc tế (ĐH Thái Nguyên)',
    'DTP': 'Phân hiệu Đại học Thái Nguyên tại Lào Cai',
    'DTC': 'Trường Đại học Công nghệ TT và Truyền thông (ĐH Thái Nguyên)',
    'DTZ': 'Trường Đại học Khoa học (ĐH Thái Nguyên)',
    'DTE': 'Trường Đại học Kinh tế - Quản trị kinh doanh (ĐH Thái Nguyên)',
    'DTK': 'Trường Đại học Kỹ thuật Công nghiệp (ĐH Thái Nguyên)',
    'DTN': 'Trường Đại học Nông lâm (ĐH Thái Nguyên)',
    'DTS': 'Trường Đại học Sư phạm (ĐH Thái Nguyên)',
    'DTY': 'Trường Đại học Y Dược (ĐH Thái Nguyên)',
    'DCA': 'Trường Đại học Chu Văn An (*)',
    'DDA': 'Trường Đại học Công nghệ Đông Á (*)',
    'DDM': 'Trường Đại học Công nghiệp Quảng Ninh',
    'VUI': 'Trường Đại học Công nghiệp Việt Trì',
    'DHP': 'Trường Đại học Quản lý và công nghệ Hải Phòng (*)',
    'DTV': 'Trường Đại học Lương Thế Vinh (*)',
    'YDD': 'Trường Đại học Điều dưỡng Nam Định',
    'HLU': 'Trường Đại học Hạ Long',
    'DKT': 'Trường Đại học Hải Dương',
    'THP': 'Trường Đại học Hải Phòng',
    'HHA': 'Trường Đại học Hàng hải',
    'DNB': 'Trường Đại học Hoa Lư',
    'HDT': 'Trường Đại học Hồng Đức',
    'THV': 'Trường Đại học Hùng Vương',
    'UKB': 'Trường Đại học Kinh Bắc (*)',
    'DKY': 'Trường Đại học Kỹ thuật Y tế Hải Dương',
    'DBG': 'Trường Đại học Nông Lâm Bắc Giang',
    'DBH': 'Trường Đại học Quốc tế Bắc Hà (*)',
    'SDU': 'Trường Đại học Sao Đỏ',
    'SP2': 'Trường Đại học Sư phạm Hà Nội 2',
    'SKH': 'Trường Đại học Sư phạm Kỹ thuật Hưng Yên',
    'SKN': 'Trường Đại học Sư phạm Kỹ thuật Nam Định',
    'DFA': 'Trường Đại học Tài chính - Quản trị kinh doanh',
    'TQU': 'Trường Đại học Tân Trào',
    'TTB': 'Trường Đại học Tây Bắc',
    'DTB': 'Trường Đại học Thái Bình',
    'DDB': 'Trường Đại học Thành Đông (*)',
    'TDB': 'Trường Đại học Thể dục Thể thao Bắc Ninh',
    'DVP': 'Trường Đại học Trưng Vương (*)',
    'DVD': 'Trường Đại học Văn hóa Thể thao và Du lịch Thanh Hóa',
    'DVB': 'Trường Đại học Việt Bắc',
    'YPB': 'Trường Đại học Y Dược Hải Phòng',
    'YTB': 'Trường Đại học Y Dược Thái Bình',
    'THU': 'Trường Đại học Y khoa Tokyo Việt Nam',

    # IV. Miền Nam
    'TAG': 'Trường Đại học An Giang (ĐHQG HCM)',
    'BVU': 'Trường Đại học Bà Rịa - Vũng Tàu (*)',
    'DBL': 'Trường Đại học Bạc Liêu',
    'DBD': 'Trường Đại học Bình Dương (*)',
    'TCT': 'Trường Đại học Cần Thơ',
    'DCD': 'Trường Đại học Công nghệ Đồng Nai (*)',
    'MIT': 'Trường Đại học Công nghệ Miền Đông (*)',
    'DCL': 'Trường Đại học Cửu Long (*)',
    'DLH': 'Trường Đại học Lạc Hồng (*)',
    'PVU': 'Trường Đại học Dầu khí Việt Nam',
    'DNU': 'Trường Đại học Đồng Nai',
    'SPD': 'Trường Đại học Đồng Tháp',
    'TKG': 'Trường Đại học Kiên Giang',
    'DLA': 'Trường Đại học Kinh tế Công nghiệp Long An (*)',
    'DKB': 'Trường Đại học Kinh tế Kỹ thuật Bình Dương (*)',
    'KCC': 'Trường Đại học Kỹ thuật Công nghệ Cần Thơ',
    'LNS': 'Trường Đại học Lâm nghiệp – Cơ sở 2',
    'DNC': 'Trường Đại học Nam Cần Thơ (*)',
    'EIU': 'Trường Đại học Quốc tế Miền Đông (*)',
    'VLU': 'Trường Đại học Sư phạm Kỹ thuật Vĩnh Long',
    'TTU': 'Trường Đại học Tân Tạo (*)',
    'DTD': 'Trường Đại học Tây Đô (*)',
    'TDM': 'Trường Đại học Thủ Dầu Một',
    'TTG': 'Trường Đại học Tiền Giang',
    'DVT': 'Trường Đại học Trà Vinh',
    'VTT': 'Trường Đại học Võ Trường Toản (*)',
    'MTU': 'Trường Đại học Xây dựng Miền Tây',
    'YCT': 'Trường Đại học Y Dược Cần Thơ',

    # V. Miền Trung - Tây Nguyên
    'DHD': 'Trường Du lịch - ĐH Huế',
    'DHC': 'Khoa Giáo dục Thể chất - ĐH Huế',
    'DHT': 'Trường Đại học Khoa học - ĐH Huế',
    'DHK': 'Trường Đại học Kinh tế - ĐH Huế',
    'DHL': 'Trường Đại học Nông Lâm - ĐH Huế',
    'DHN': 'Trường Đại học Nghệ thuật - ĐH Huế',
    'DHA': 'Trường Đại học Luật - ĐH Huế',
    'DHF': 'Trường Đại học Ngoại ngữ - ĐH Huế',
    'DHS': 'Trường Đại học Sư phạm - ĐH Huế',
    'DHY': 'Trường Đại học Y Dược - ĐH Huế',
    'DHE': 'Khoa Kỹ thuật và công nghệ - ĐH Huế',
    'DHI': 'Khoa Quốc tế - ĐH Huế',
    'DHQ': 'Phân hiệu ĐH Huế tại Quảng Trị',
    'DDG': 'Khoa Giáo dục Thể chất – ĐH Đà Nẵng',
    'DDY': 'Khoa Y Dược – ĐH Đà Nẵng',
    'DDP': 'Phân hiệu Đại học Đà Nẵng tại Kon Tum',
    'DDK': 'Trường Đại học Bách Khoa - ĐH Đà Nẵng',
    'DDQ': 'Trường Đại học Kinh tế - ĐH Đà Nẵng',
    'DDF': 'Trường Đại học Ngoại ngữ - ĐH Đà Nẵng',
    'DDS': 'Trường Đại học Sư phạm - ĐH Đà Nẵng',
    'DSK': 'Trường Đại học Sư phạm Kỹ thuật – ĐH Đà Nẵng',
    'DDV': 'Viện nghiên cứu đào tạo Việt - Anh - ĐH Đà Nẵng',
    'VKU': 'Khoa Công nghệ thông tin và Truyền thông – ĐH Đà Nẵng',
    'KTD': 'Trường Đại học Kiến trúc Đà Nẵng (*)',
    'BMU': 'Trường Đại học Y dược Buôn Ma Thuột (*)',
    'DVX': 'Trường Đại học Công nghệ Vạn Xuân (*)',
    'DCV': 'Trường Đại học Công nghiệp Vinh (*)',
    'TDL': 'Trường Đại học Đà Lạt',
    'DDT': 'Trường Đại học Duy Tân (*)',
    'DPX': 'Trường Đại học Dân lập Phú Xuân (*)',
    'DYD': 'Trường Đại học Yersin Đà Lạt (*)',
    'DAD': 'Trường Đại học Đông Á (*)',
    'HHT': 'Trường Đại học Hà Tĩnh',
    'UKH': 'Trường Đại học Khánh Hòa',
    'CEA': 'Trường Đại học Kinh tế Nghệ An',
    'YDN': 'Trường Đại học Kỹ thuật Y Dược Đà Nẵng',
    'HVA': 'Học viện Âm nhạc Huế',
    'TSN': 'Trường Đại học Nha Trang',
    'DPQ': 'Trường Đại học Phạm Văn Đồng',
    'DPC': 'Trường Đại học Phan Châu Trinh (*)',
    'DPT': 'Trường Đại học Phan Thiết (*)',
    'DPY': 'Trường Đại học Phú Yên',
    'DQB': 'Trường Đại học Quảng Bình',
    'DQU': 'Trường Đại học Quảng Nam',
    'DQT': 'Trường Đại học Quang Trung (*)',
    'DQN': 'Trường Đại học Quy Nhơn',
    'SKV': 'Trường Đại học Sư phạm Kỹ thuật Vinh',
    'UFA': 'Trường Đại học Tài chính Kế toán',
    'TTN': 'Trường Đại học Tây Nguyên',
    'TBD': 'Trường Đại học Thái Bình Dương (*)',
    'TTD': 'Trường Đại học Thể dục Thể thao Đà Nẵng',
    'TDV': 'Trường Đại học Vinh',
    'XDT': 'Trường Đại học Xây dựng Miền Trung',
    'YKV': 'Trường Đại học Y khoa Vinh',

    # VI. Quân đội - Công an
    'BPH': 'Học viện Biên phòng',
    'HQH': 'Học viện Hải Quân',
    'HEH': 'Học viện Hậu cần',
    'NQH': 'Học viện Khoa học Quân sự',
    'KQH': 'Học viện Kỹ thuật Quân sự',
    'PKH': 'Học viện Phòng không - Không quân',
    'YQH': 'Học viện Quân Y',
    'LCH': 'Trường Đại học Chính trị (Trường Sĩ quan Chính trị)',
    'ZNH': 'Trường Đại học Văn hóa - Nghệ thuật Quân đội',
    'SNH': 'Trường Sĩ quan Công binh',
    'DCH': 'Trường Sĩ quan Đặc công',
    'KGH': 'Trường Sĩ quan Không quân',
    'VPH': 'Trường Sĩ quan Kỹ thuật QS Vinhempich (ĐH Trần Đại Nghĩa)',
    'LAH': 'Trường Sĩ quan Lục quân 1 (ĐH Trần Quốc Tuấn)',
    'LBH': 'Trường Sĩ quan Lục quân 2 (ĐH Nguyễn Huệ)',
    'PBH': 'Trường Sĩ quan Pháo binh',
    'HGH': 'Trường Sĩ quan Phòng Hóa',
    'TGH': 'Trường Sĩ quan Tăng - Thiết giáp',
    'TTH': 'Trường Sĩ quan Thông tin',
    'ANH': 'Học viện An ninh Nhân dân',
    'CSH': 'Học viện Cảnh sát Nhân dân',
    'HCA': 'Học viện Chính trị Công an Nhân dân',
    'ANS': 'Trường Đại học An ninh nhân dân',
    'CSS': 'Trường Đại học Cảnh sát nhân dân',
    'HCB': 'Trường Đại học Kỹ thuật - Hậu cần Công an nhân dân phía Bắc',
    'HCN': 'Trường Đại học Kỹ thuật - Hậu cần Công an nhân dân phía Nam',
    'PCH': 'Trường Đại học Phòng cháy chữa cháy phía Bắc',
    'PCS': 'Trường Đại học Phòng cháy chữa cháy phía Nam',
}
